version: 0.1
auth:
  token:
    realm: http://cabotage-app:5001/auth
    service: cabotage-registry
    issuer: cabotage-app
    rootcertbundle: /etc/docker/registry-local/public_key_bundle
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
