name: Publish
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  packages: write
jobs:
  release-to-ghcr:
    concurrency:
      group: release-to-ghcr
      cancel-in-progress: false
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-24.04, arch: amd64 }
          - { os: ubuntu-24.04-arm, arch: arm64 }
    steps:
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login To GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/cabotage/cabotage-app:${{ github.sha }}-${{ matrix.config.arch }}
            ghcr.io/cabotage/cabotage-app:latest-${{ matrix.config.arch }}

    create-manifests:
      runs-on: ubuntu-24.04-arm
      needs: [release-to-ghcr]

      steps:
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login To GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create SHA manifest and push
        run:
          docker manifest create \
            ghcr.io/cabotage/cabotage-app:${{ github.sha }} \
            --amend ghcr.io/cabotage/cabotage-app:${{ github.sha }}-amd64 \
            --amend ghcr.io/cabotage/cabotage-app:${{ github.sha }}-arm64
          docker manifest push ghcr.io/cabotage/cabotage-app:${{ github.sha }}

      - name: Create latest manifest and push
        run: |
          docker manifest create \
            ghcr.io/cabotage/cabotage-app:latest \
            --amend ghcr.io/cabotage/cabotage-app:latest-amd64 \
            --amend ghcr.io/cabotage/cabotage-app:latest-arm64
          docker manifest push ghcr.io/cabotage/cabotage-app:latest
